### ISSUE TITLE
This module uses the depreciated concat_native module

### ISSUE THREAD

**Issue by savingschampion** [mcanevet/puppet-btsync#13]
Deprecation warning

This module is deprecated in favour of puppetlabs-concat 2.0.0 or higher.

It used to be a better alternative than the 1.x series by being implemented as a native type instead of shell scripts, but 2.x rewrote concat as native types. theforeman modules will be updated to use puppetlabs-concat and this module will not be maintained.

https://forge.puppetlabs.com/theforeman/concat_native

**Comment by mcanevet** [comment]
@savingschampion the problem is that this module uses concat sub fragments and this feature is not supported in `puppetlabs-concat`. I'll try to use augeas instead.

**Comment by savingschampion** [comment]
I've managed to use KyleAnderson/btsync with puppetlabs-concat, so you may want to see how he has done it?

**Comment by darkpixel** [comment]
+1

**Comment by mcanevet** [comment]
Fixed by #16
